function font-test --description "Print various text styles in terminal."
    echo -e "normal"
    echo -e "\e[1mbold\e[0m"
    echo -e "\e[3mitalic\e[0m"
    echo -e "\e[4munderline\e[0m"
    echo -e "\e[9mstrikethrough\e[0m"
    echo -e "\e[31mRed\e[0m"
    echo -e "\x1B[31mOther red\e[0m"
    echo -e "\e[3;4;33mYellow, underline, italic\e[0m"
    echo -e "\e[1;3;4mBold, underline, italic\e[0m"
end
